image:
  name: nexus.mosaicsmartdata.com:8083/mosaicsmartdata/msq-docker:latest
  username: $DOCKER_REPO_USERNAME
  password: $DOCKER_REPO_PASSWORD
  email: james@mosaicsmartdata.com
pipelines:
  custom:
    clean-build:
      - step:
          script:
            - docker login nexus.mosaicsmartdata.com:8083 -u $DOCKER_REPO_USERNAME -p $DOCKER_REPO_PASSWORD
            - export KAFKA_BROKER=localhost
            - pyb install_dependencies
            - pyb clean publish
          services:
            - zookeeper
            - kafka
  branches:
    master:
      - step:
          script:
            - docker login nexus.mosaicsmartdata.com:8083 -u $DOCKER_REPO_USERNAME -p $DOCKER_REPO_PASSWORD
            - export KAFKA_BROKER=localhost
            - pyb install_dependencies
            - bash msx.sh bitbucket_pyb
            - bash msx.sh bitbucket_docker_build_push
          services:
            - zookeeper
            - kafka
definitions:
  services:
    zookeeper:
      image: wurstmeister/zookeeper
    kafka:
      image: wurstmeister/kafka
      environment:
        KAFKA_ADVERTISED_HOST_NAME: "localhost"
options:
  docker: true
