image:
  name: nexus.mosaicsmartdata.com:8083/mosaicsmartdata/msq-docker
  username: $DOCKER_REPO_USERNAME
  password: $DOCKER_REPO_PASSWORD
  email: james@mosaicsmartdata.com
pipelines:
  custom:
    clean-build:
      - step:
          script:
            - docker login nexus.mosaicsmartdata.com:8083 -u $DOCKER_REPO_USERNAME -p $DOCKER_REPO_PASSWORD
  branches:
    master:
      - step:
          script:
            - docker login nexus.mosaicsmartdata.com:8083 -u $DOCKER_REPO_USERNAME -p $DOCKER_REPO_PASSWORD
options:
  docker: true
